#!/usr/bin/env python3
"""Round-h branch scoring under audit/FREEZE_2026-10-02h (committed first). Order fixed by the freeze: GZ-1 validations V1, V2 (PDG/CODATA
inputs only), then the branches GZ-1 (H1, H2), DM-R1, T-1, MUD-1. Record values are not changed.

  python tools/score_2026_10_02h.py --hub <FSOT-2.1-Lean @ 6f9c2560> --out audit/score_2026-10-02h.tsv [--validate-only]
"""
import argparse, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
import fsot02d as X
from fsot02d import mpf, sqrt, pi, ln, fabs, nstr
from mpmath import zeta
ap = argparse.ArgumentParser(); ap.add_argument("--hub", required=True); ap.add_argument("--out", required=True)
ap.add_argument("--validate-only", action="store_true"); a = ap.parse_args()
rows = []
def emit(sec, name, inputs, v, c, s, note=""):
    zz = fabs(v - c) / s
    rows.append([sec, name, inputs, nstr(v, 15), nstr(c, 12), nstr(s, 5), nstr(zz, 5), "PASS" if zz <= 1 else "FAIL", nstr((v - c) / c * 10**6, 6), note])
def info(sec, name, inputs, v, note=""):
    rows.append([sec, name, inputs, nstr(v, 15), "-", "-", "-", "info", "-", note])
def write():
    with open(a.out, "w") as o:
        o.write("# generated by tools/score_2026_10_02h.py under audit/FREEZE_2026-10-02h (committed first)\n#section\tname\tinputs\tvalue\tcentral\tsigma\tz\tz<=1\tppm\tnote\n")
        for r in rows: o.write("\t".join(str(x) for x in r) + "\n")
ref = X.refs(); z3 = zeta(3)

# ---- GZ-1 building blocks (hep-ph/0311148; arXiv:1401.2447)
def mw_acfw(MH, mt, MZ, dal, als):  # eqs. fitformula, pardef, fitparams
    dH = ln(MH / 100); dh = (MH / 100) ** 2; dt = (mt / mpf("174.3")) ** 2 - 1; dZ = MZ / mpf("91.1875") - 1
    da = dal / mpf("0.05907") - 1; das = als / mpf("0.119") - 1
    return (mpf("80.3779") - mpf("0.05427") * dH - mpf("0.008931") * dH**2 + mpf("0.0000882") * dH**4 + mpf("0.000161") * (dh - 1)
            - mpf("1.070") * da + mpf("0.5237") * dt - mpf("0.0679") * dt**2 - mpf("0.00179") * dH * dt + mpf("0.0000664") * dh * dt
            - mpf("0.0795") * das + mpf("114.9") * dZ)
GZC = [mpf(x) for x in "2494.24 -3.725 -2.019 1.773 -0.04554 19.63 -2.0 -0.36 0.257 58.60 -4.1 -0.53 7.6 -56.0 1.3 9256".split()]
def gz_freitas(MH, mt, MZ, dal, als):  # eq. par2, tab:fit2 row Gamma_Z, MeV -> GeV
    LH = ln(MH / mpf("125.7")); DH = MH / mpf("125.7") - 1; Dt = (mt / mpf("173.2")) ** 2 - 1; Das = als / mpf("0.1184") - 1
    Da = dal / mpf("0.059") - 1; DZ = MZ / mpf("91.1876") - 1; c = GZC
    return (c[0] + c[1] * LH + c[2] * LH**2 + c[3] * DH + c[4] * DH**2 + c[5] * Dt + c[6] * Dt**2 + c[7] * Dt * LH + c[8] * Dt * LH**2
            + c[9] * Das + c[10] * Das**2 + c[11] * Das * LH + c[12] * Das * Dt + c[13] * Da + c[14] * Da * LH + c[15] * DZ) / 1000
def gamma_w(G, MW, als): return 3 * G * MW**3 / (2 * sqrt(2) * pi) * (1 + 2 * als / (3 * pi))
def pole(M, G): return M / sqrt(1 + (G / M) ** 2)
G_ACFW, AL_ACFW, GZ_ACFW, G_FR = mpf("1.166379e-5"), 1 / mpf("137.03599976"), mpf("2.4952"), mpf("1.16638e-5")
def delta_r(MH, mt, MZ, dal, als):
    MW = mw_acfw(MH, mt, MZ, dal, als); mwb, mzb = pole(MW, gamma_w(G_ACFW, MW, als)), pole(MZ, GZ_ACFW)
    return sqrt(2) * G_ACFW * mwb**2 * (1 - mwb**2 / mzb**2) / (pi * AL_ACFW) - 1, MW
def gf_from(al, MW, MZ, dr, als, GZ):
    G = mpf("1.1663787e-5")
    for _ in range(60):
        mwb, mzb = pole(MW, gamma_w(G, MW, als)), pole(MZ, GZ)
        new = pi * al * (1 + dr) / (sqrt(2) * mwb**2 * (1 - mwb**2 / mzb**2))
        if fabs(new - G) / G < mpf(10) ** -25: return new
        G = new
    return G
def d_s(s2, als):
    fs = [(-1, -mpf(1) / 2, 1, 3), (0, mpf(1) / 2, 1, 3), (mpf(2) / 3, mpf(1) / 2, 3 * (1 + als / pi), 2), (-mpf(1) / 3, -mpf(1) / 2, 3 * (1 + als / pi), 3)]
    num = sum(n * w * 2 * (T - 2 * Q * s2) * (-2 * Q) for Q, T, w, n in fs); den = sum(n * w * ((T - 2 * Q * s2) ** 2 + T**2) for Q, T, w, n in fs)
    return num / den
def dalep(al, MZ, masses):
    return (al / (3 * pi) * sum(ln(MZ**2 / m**2) - mpf(5) / 3 for m in masses)
            + (al / pi) ** 2 * sum(ln(MZ**2 / m**2) / 4 + z3 - mpf(5) / 24 for m in masses))

# ---- (1) validations, PDG/CODATA inputs only
sec = "validation"; alC = 1 / mpf("137.035999177")
dlv = dalep(alC, mpf("91.1880"), [mpf("0.51099895e-3"), mpf("0.1056583755"), mpf("1.77693")]); dav = dlv + mpf("0.02783")
info(sec, "Delta alpha (lep+had)", "round-f lepton formula with PDG masses + 0.02783", dav)
V1 = mw_acfw(mpf("125.10"), mpf("172.61"), mpf("91.1880"), dav, mpf("0.1180"))
emit(sec, "V1 M_W GeV (ACFW)", "M_H 125.10, m_t 172.61, M_Z 91.1880, alpha_s 0.1180", V1, *ref("M_W_SM_GeV"), "criterion |dev| <= 0.006")
V2 = gz_freitas(mpf("125.20"), mpf("172.57"), mpf("91.1880"), dav, mpf("0.1180"))
emit(sec, "V2 Gamma_Z GeV (Freitas)", "M_H 125.20, m_t 172.57, M_Z 91.1880, alpha_s 0.1180", V2, *ref("Gamma_Z_SM_GeV"), "criterion |dev| <= 0.0009")
VALID = fabs(V1 - mpf("80.353")) <= mpf("0.006") and fabs(V2 - mpf("2.4940")) <= mpf("0.0009")
drv, _ = delta_r(mpf("125.20"), mpf("172.57"), mpf("91.1880"), dav, mpf("0.1180"))
info(sec, "Delta r (ACFW, PDG inputs)", "read back from eq. MW", drv, "ACFW convention (1+Delta r), complex-pole masses")
G3 = gf_from(alC, mpf("80.3692"), mpf("91.1880"), drv, mpf("0.1180"), V2)
emit(sec, "V3 G_F from measured M_W (informational)", "PDG inputs, M_W 80.3692", G3, *ref("G_F_GeVm2"), "informational only")
info(sec, "VALIDATED", "V1 and V2 pass", mpf(1 if VALID else 0), "1 = GZ-1 validated, 0 = not validated (nothing from GZ-1 confirmed)")
if a.validate_only:
    write(); print("validation only; VALID =", VALID); sys.exit(0)

# ---- (2) branches with FSOT inputs
hub, F = X.setup(a.hub); P = X.pins(); L = X.leaves()
MZ, MW, al = L["m_Z_MeV"] / 1000, L["m_W_MeV"] / 1000, 1 / L["alpha_inv"]
mt = L["m_t_over_m_W"] * MW; MH = L["m_H_MeV"] / 1000; als = 2 * (F.POOF / F.PSI_CON) ** 2; mtau = L["m_tau_MeV"] / 1000
dl = dalep(al, MZ, [X.kg_to_GeV(L["m_e_kg"]), X.kg_to_GeV(L["m_mu_kg"]), mtau])
ds = d_s(L["sin2_theta_W_MSbar"], als); s2leaf = 1 - (MW / MZ) ** 2
info("GZ-1", "Delta alpha_lep (FSOT)", "round-f formula (frozen 0.0314983607415527)", dl); info("GZ-1", "d_s = dlnGamma_Z/ds2 (Born)", "", ds)
for H, dh, tag in (("H1", mpf("0.0241044885083033"), "PRIMARY (FSOT-only)"), ("H2", mpf("0.02783"), "secondary (external Delta alpha_had)")):
    S = f"GZ-1_{H}"; dal = dl + dh
    dr, MWfit = delta_r(MH, mt, MZ, dal, als)
    GZ = GZ_ACFW
    for _ in range(30):
        G = gf_from(al, MW, MZ, dr, als, GZ)
        GZfit = gz_freitas(MH, mt, MZ, dal, als); dS2 = s2leaf - (1 - (MWfit / MZ) ** 2)
        new = GZfit * (G / G_FR) * (1 + ds * dS2)
        if fabs(new - GZ) < mpf(10) ** -15: GZ = new; break
        GZ = new
    info(S, "Delta alpha", tag, dal); info(S, "M_W^fit GeV (ACFW, CODATA-like G_mu)", "SM M_W at FSOT inputs", MWfit)
    info(S, "Delta r (complete SM, ACFW)", tag, dr, "ACFW convention (1+Delta r), complex-pole masses; not comparable digit-for-digit with the PDG 0.03685 (1/(1-Delta r) convention)")
    emit(S, "G_F GeV^-2", tag, G, *ref("G_F_GeVm2"), "frozen-pending")
    info(S, "Gamma_Z^fit GeV (Freitas, G_mu internal)", "", GZfit); info(S, "s2 mapping delta", "s2_OS(leaf) - s2_OS(M_W^fit)", dS2)
    note = ("confirms only if V1, V2 pass and z<=1" + ("" if VALID else " -- VALIDATION FAILED: not confirmable")) if H == "H1" else "never confirmed (external)"
    emit(S, "Gamma_Z/M_Z", "GZ-1", GZ / MZ, *ref("Gamma_Z_over_M_Z"), note)
    emit(S, "Gamma_Z GeV", "GZ-1", GZ, *ref("Gamma_Z_GeV"), "frozen-pending")
# DM-R1
c21, s21 = ref("dm2_21"); c32, s32 = ref("dm2_32"); Sm = c21 + c32
c = c21 / Sm; s = sqrt((c32 / Sm**2 * s21) ** 2 + (c21 / Sm**2 * s32) ** 2)
emit("DM-R1", "gamma^3 Poof vs Dm2_21/Dm2_31 (NO)", "formula unchanged; reference object Dm2_31 = Dm2_32 + Dm2_21 (PDG 2024)", P["wave4|Dm2_21/Dm2_32"], c, s,
     "decision item: record row unchanged (object choice is Damian's)")
# T-1
kB, hbar, c0 = mpf("1.380649e-23"), X.H_PLANCK / (2 * pi), X.C_LIGHT
Mpc = mpf(648000) / pi * mpf("149597870700") * 10**6
rho_c100 = 3 * (mpf(10) ** 5 / Mpc) ** 2 / (8 * pi * L["G_N"])
A = (pi**2 / 15) * kB**4 / (hbar**3 * c0**5) / rho_c100
fnu = mpf(7) / 8 * (mpf(4) / 11) ** (mpf(4) / 3) * mpf("3.044")
h = P["wave1|H0"] / 100; Om = P["wave2|Omega_m"]; zeq = P["wave3|z_eq"]
T = (Om * h**2 / ((1 + zeq) * A * (1 + fnu))) ** (mpf(1) / 4)
info("T-1", "Omega_gamma h^2 / T^4 [K^-4]", "constants, FSOT G_N", A); info("T-1", "z_eq, Omega_m, h (FSOT pins)", "", zeq, f"Omega_m {nstr(Om, 10)}, h {nstr(h, 10)}")
emit("T-1", "T_CMB K (radiation-matter equality)", "FSOT z_eq, Omega_m, H0, G_N; N_eff 3.044", T, *ref("T0_K"), "frozen-pending if passing")
# MUD-1
mun = -mpf(2) / 3 * L["mu_p_over_mu_N"]
emit("MUD-1", "mu_n (SU(6) from FSOT mu_p)", "intermediate", mun, *ref("mu_n_over_mu_N"), "intermediate")
emit("MUD-1", "mu_d = mu_p + mu_n (S-state, P_D = 0)", "SU(6) mu_n", L["mu_p_over_mu_N"] + mun, *ref("mu_d_over_mu_N"), "frozen-pending if passing")
write()
