#!/usr/bin/env python3
"""Round-ah scores under audit/FREEZE_2026-10-02ah (committed first). z-only, dimensionless ratios; FSOT-only inputs.
AH-1 mu_V^(0) kmax scan (audit/kscan_2026-10-02ah.json); AH-2 full valence + PV-sea scalar charge and g_sigmaNN (audit/sigsea_2026-10-02ah.json).
  python tools/score_2026_10_02ah.py --hub <FSOT-2.1-Lean @ 6f9c2560> --out audit/score_2026-10-02ah.tsv
"""
import argparse, json, math, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
import fsot02d as X
from fsot02d import mpf, sqrt, pi, ln, fabs, nstr
from mpmath import zeta
ap = argparse.ArgumentParser(); ap.add_argument("--hub", required=True); ap.add_argument("--out", required=True); a = ap.parse_args()
hub, F = X.setup(a.hub); L = X.leaves(); P = X.pins(); ref = X.refs(); R_ = Path(__file__).resolve().parents[1]
rows = []
def emitz(sec, name, inputs, v, c, s, th=0, cls="", note=""):
    v, c, s, th = mpf(v), mpf(c), mpf(s), mpf(th); sig = sqrt(s**2 + th**2); z = fabs(v - c) / sig
    rows.append([sec, name, inputs, nstr(v, 12), nstr(c, 10), nstr(sig, 4), nstr(z, 5), "agrees" if z <= 1 else "miss", nstr((v - c) / c * 100, 5) + " %", cls, note]); return z
def info(sec, name, inputs, v, cls="", note=""): rows.append([sec, name, inputs, nstr(mpf(v), 12), "-", "-", "-", "info", "-", cls, note])
def rec(sec, name, verdict, note): rows.append([sec, name, "-", "-", "-", "-", "-", verdict, "-", "-", note])
J = lambda f: json.loads((R_ / f).read_text(encoding="utf-8"))
mpM = X.kg_to_GeV(L["m_p_kg"]) * 1000
# ---------------- AD-1
def col(path, sec, key):
    for line in open(R_ / path, encoding="utf-8"):
        f = line.rstrip("\n").split("\t")
        if len(f) > 3 and f[0] == sec and f[1].startswith(key): return mpf(f[3])
Hw = J("audit/heavy_2026-10-02ab_wide_K12.json")
# ---------------- AH-1
s = "AH-1"
KS = J("audit/kscan_2026-10-02ah.json"); Mr1 = mpf(J("audit/murun_2026-10-02ag_K14_D14_k12.json")["inputs"]["M_over_mp"])
mv = []
for e_ in KS["scan"]:
    m0 = -(1 / Mr1) / 3 * (mpf(e_["xat_val"]) + mpf(e_["xat_sea"])); mv.append(m0)
    info(s, "AH-1 mu_V^(0) at kmax %g (K 14, D 14)" % e_["kmax"], "kmax-12 profile, M_PV/M %s" % nstr(mpf(KS["Mpv_over_M"]), 7), m0, "diagnostic",
         "xat_val %s; xat_sea %s = bare sea - vac %s + PV part %s (PV/bare %s); %s s" % (nstr(mpf(e_["xat_val"]), 8), nstr(mpf(e_["xat_sea"]), 7), nstr(mpf(e_["bare_minus_vac"]), 7), nstr(mpf(e_["pv_minus_vacpv_weighted"]), 7), nstr(-mpf(e_["pv_minus_vacpv_weighted"]) / mpf(e_["bare_minus_vac"]), 4), e_["seconds"]))
ch = [(mv[i + 1] - mv[i]) / mv[i + 1] for i in range(len(mv) - 1)]
if all(fabs(c_) <= mpf("0.02") for c_ in ch):
    rec(s, "AH-1 mu_V^(0) kmax stability", "stable", "changes " + ", ".join(nstr(c_ * 100, 3) + " %" for c_ in ch) + "; full kmax-16 run required before scoring (not run)")
else:
    rec(s, "AH-1 mu_p, mu_n", "not scored", "mu_V^(0) kmax 12 -> 14 -> 16 changes " + ", ".join(nstr(c_ * 100, 3) + " %" for c_ in ch) + " (non-monotone; 2 % rule fails); rotational Amu, B move <= 0.6 % (rounds ae/ag runs)")
# ---------------- AH-2
s = "AH-2"
SG = J("audit/sigsea_2026-10-02ah.json"); r12, r14 = SG["runs"][0], SG["runs"][1]
Fr = col("audit/score_2026-10-02p.tsv", "FSOT", "P-4 F_pi with lbar4") / mpM; Mq = mpf(Hw["inputs"]["M_over_mp"])
for r_ in (r12, r14):
    gs2f = (mpf(r_["Q_full"]) * Mq / Fr)**2 / (4 * pi)
    info(s, "AH-2 full scalar charge Integral S (kmax %g)" % r_["kmax"], "round-ab soliton, K 12, D 12", r_["Q_full"], "FSOT · intermediate",
         "valence %s (= 3 S_val), PV-regularised sea %s; g_sigmaNN^2/4pi would be %s (valence-only 3.966); r_S^2 M^2 full %s (valence %s), Lambda_S/m_p %s" % (nstr(mpf(r_["Q_val"]), 7), nstr(mpf(r_["Q_sea"]), 7), nstr(gs2f, 5), nstr(mpf(r_["r2_full"]), 6), nstr(mpf(r_["r2_val"]), 6), nstr(sqrt(6) / (sqrt(mpf(r_["r2_full"])) / Mq), 5)))
chg = (mpf(r14["Q_full"]) - mpf(r12["Q_full"])) / mpf(r14["Q_full"])
if fabs(chg) <= mpf("0.02"):
    rec(s, "AH-2 adoption", "adopted", "kmax 12 -> 14 change %s %%" % nstr(chg * 100, 3))
else:
    rec(s, "AH-2 full g_sigmaNN", "not adopted; deuteron not rerun, nothing scored", "Integral S kmax 12 -> 14 change %s %% (sea %s %%) > 2 %%: the single-PV scalar density keeps its log-divergent piece" % (nstr(chg * 100, 3), nstr((mpf(r14["Q_sea"]) - mpf(r12["Q_sea"])) / mpf(r14["Q_sea"]) * 100, 3)))
rec("GATE", "record rows of the 91", "unchanged", "z-only")
with open(a.out, "w", encoding="utf-8", newline="\n") as o:
    o.write("# generated by tools/score_2026_10_02ah.py under audit/FREEZE_2026-10-02ah (committed first)\n#section\tname\tinputs\tvalue\tcentral\tsigma\tz\tverdict\trel\tclass\tnote\n")
    for r_ in rows: o.write("\t".join(str(x_) for x_ in r_) + "\n")
print("done", len(rows))
