#!/usr/bin/env python3
"""Scoring under docs/freezes/DERIVATIONS_2026-10-02g (committed first): effective Z couplings (LEPTOP, hep-ph/9503308) in the Gamma_Z width
construction. Order fixed by the freeze: (1) transcription checks against LEPTOP's own printed numbers, (2) pre-declared validation with
PDG/CODATA inputs only, (3) FSOT inputs H1 (primary), H2 (secondary), H2c (diagnostic).

  python tools/score_2026_10_02g.py --hub <FSOT-2.1-Lean @ 6f9c2560> --out audit/score_2026-10-02g.tsv [--validate-only]
"""
import argparse, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
import fsot02d as X
from fsot02d import mpf, sqrt, pi, ln, fabs, nstr
from mpmath import zeta
import zwidth_g as W
ap = argparse.ArgumentParser(); ap.add_argument("--hub", required=True); ap.add_argument("--out", required=True)
ap.add_argument("--validate-only", action="store_true"); a = ap.parse_args()
rows = []
def emit(sec, name, inputs, v, c, s, note=""):
    zz = fabs(v - c) / s
    rows.append([sec, name, inputs, nstr(v, 15), nstr(c, 12), nstr(s, 5), nstr(zz, 5), "PASS" if zz <= 1 else "FAIL", nstr((v - c) / c * 10**6, 6), note])
def info(sec, name, inputs, v, note=""):
    rows.append([sec, name, inputs, nstr(v, 15), "-", "-", "-", "info", "-", note])
def write():
    with open(a.out, "w") as o:
        o.write("# generated by tools/score_2026_10_02g.py under docs/freezes/DERIVATIONS_2026-10-02g (committed first)\n#section\tname\tinputs\tvalue\tcentral\tsigma\tz\tz<=1\tppm\tnote\n")
        for r in rows: o.write("\t".join(str(x) for x in r) + "\n")
ref = X.refs(); z3 = zeta(3)
def dalep(al, MZ, masses):
    return (al / (3 * pi) * sum(ln(MZ**2 / m**2) - mpf(5) / 3 for m in masses)
            + (al / pi) ** 2 * sum(ln(MZ**2 / m**2) / 4 + z3 - mpf(5) / 24 for m in masses))
HB = X.HBARC_GEV_FM**2 * mpf(10) ** 7

# ---- (1) transcription checks: LEPTOP's own printed numerical values (m_t = 175, s^2 = 0.23117 region); code-correctness only
sec = "transcription"
s2r = mpf("0.23117"); c2r = 1 - s2r; tr = (mpf(175) / mpf("91.1888")) ** 2
dWa = 1 / (2 * pi) * ((3 + 4 * c2r) * (1 - sqrt(4 * c2r - 1) * W.asin(1 / (2 * sqrt(c2r)))) - mpf(1) / 3)
dta = -4 / (9 * pi) * ((1 + 2 * tr) * W.F_t(tr) - mpf(1) / 3)
for nm, v, c, tol in [("delta_W alpha/alpha (eq. 307)", dWa, "0.0686", "0.00005"), ("delta_t alpha/alpha (eq. 308)", dta, "-0.00768", "0.000005"),
                      ("delta_1 V_m (eq. 405)", -mpf(16) / 3 * pi * s2r**2 * (dWa + dta), "-0.055", "0.0005"),
                      ("delta_1 V_R (eq. 38)", -mpf(16) / 3 * pi * s2r * c2r * (dWa + dta), "-0.181", "0.0005"),
                      ("delta_2^q V_m / (alpha_s/pi) (eq. 309)", 2 * mpf(4) / 3 * (c2r - s2r) * ln(c2r), "-0.377", "0.0005"),
                      ("delta_2^q V_A / (alpha_s/pi) (eq. 310)", 2 * mpf(4) / 3 * (c2r - s2r + mpf(20) / 9 * s2r**2), "1.750", "0.0005"),
                      ("delta_2^t V_A / (alpha_s(m_t)/pi) (eq. 313)", -mpf("2.86") * tr + mpf("0.493") - mpf("0.19") / tr - mpf("0.05") / tr**2, "-10.10", "0.005"),
                      ("A(300/175) table 1 (eq. 316 text)", W.tab1(mpf(300) / 175)[0], "8.9", "0.05"),
                      ("tau_b(300/175) table 1 (eq. 403 text)", W.tab1(mpf(300) / 175)[1], "1.245", "0.0015")]:
    emit(sec, nm, "LEPTOP printed value at m_t=175", v, mpf(c), mpf(tol), "code check (tolerance = last printed digit)")

# ---- (2) validation, PDG/CODATA inputs only
MZv = mpf("91.1876"); alv = 1 / mpf("137.035999177")
dlv = dalep(alv, MZv, [mpf("0.51099895e-3"), mpf("0.1056583755"), mpf("1.77693")])
vin = dict(G_mu=mpf("1.1663787e-5"), MZ=MZv, alpha_bar=alv / (1 - dlv - mpf("0.02783")), mt=mpf("172.57"), mH=mpf("125.20"),
           alpha_s=mpf("0.1180"), mb=mpf("4.183"), mc=mpf("1.2730"), mtau=mpf("1.77693"))
V = W.compute(vin); sec = "validation"
info(sec, "Delta alpha_lep", "round-f 1+2 loop formula, PDG lepton masses", dlv); info(sec, "1/alpha_bar", "", 1 / vin["alpha_bar"])
info(sec, "s^2 (eq. 303)", "", V["s2"]); info(sec, "mhat_b(M_Z) GeV", "2-loop running", V["mb_MZ"]); info(sec, "mhat_c(M_Z) GeV", "2-loop running", V["mc_MZ"])
info(sec, "m_W GeV (eq. 31, info)", "", V["mW_over_mZ"] * MZv)
emit(sec, "Gamma_Z GeV", "VALIDATION criterion |dev| <= 0.0009", V["Gamma_Z"], *ref("Gamma_Z_SM_GeV"), "PDG 2024 SM prediction eq. 10.78")
VALID = fabs(V["Gamma_Z"] - mpf("2.4940")) <= mpf("0.0009")
emit(sec, "R_e", "informational", V["R_ell"], *ref("R_e_SM"), "vs SM Table 10.5")
emit(sec, "R_b", "informational", V["R_b"], *ref("R_b_SM"), "vs SM Table 10.5")
emit(sec, "R_c", "informational", V["R_c"], *ref("R_c_SM"), "vs SM Table 10.5")
emit(sec, "sigma_had0 nb", "informational", V["sigma_had0_GeVm2"] * HB, *ref("sigma_had0_SM_nb"), "vs SM Table 10.5")
emit(sec, "sin2_eff_lept", "informational", V["sin2_eff"], *ref("sin2_eff_lept_SM"), "vs SM Table 10.5")
info(sec, "VALIDATION", "Gamma_Z within 0.0009 of 2.4940", mpf(1 if VALID else 0), "1 = validated, 0 = not validated (then nothing confirmed)")
if a.validate_only:
    write(); print("validation only; VALID =", VALID); sys.exit(0)

# ---- (3) FSOT inputs
hub, F = X.setup(a.hub); P = X.pins(); L = X.leaves()
MZ, al = L["m_Z_MeV"] / 1000, 1 / L["alpha_inv"]
mt = L["m_t_over_m_W"] * L["m_W_MeV"] / 1000; mb = mt / P["wave8|m_t/m_b"]; mc = L["m_c_over_m_b"] * mb; mH = L["m_H_MeV"] / 1000
mtau = L["m_tau_MeV"] / 1000; als = 2 * (F.POOF / F.PSI_CON) ** 2
dl = dalep(al, MZ, [X.kg_to_GeV(L["m_e_kg"]), X.kg_to_GeV(L["m_mu_kg"]), mtau])
qcd = 1 - mpf(2) / 3 * (1 + pi**2 / 3) * als / pi
sec = "inputs"
info(sec, "m_Z GeV", "leaf", MZ); info(sec, "m_t GeV", "m_t/m_W leaf * m_W", mt); info(sec, "m_H GeV", "leaf", mH); info(sec, "alpha_s(M_Z)", "2(POOF/psi_con)^2", als)
info(sec, "m_b(m_b) GeV", "m_t / wave8|m_t/m_b", mb); info(sec, "m_c(m_c) GeV", "m_c/m_b leaf * m_b", mc); info(sec, "m_tau GeV", "leaf", mtau)
info(sec, "Delta alpha_lep", "round f formula (check vs frozen 0.0314983607415527)", dl)
cases = {"H1": (mpf("1.15871442991562e-5"), mpf("0.0241044885083033"), "PRIMARY (FSOT-only)"),
         "H2": (mpf("1.16305018497583e-5"), mpf("0.02783"), "secondary (external Delta alpha_had)"),
         "H2c": (mpf("1.1663787e-5"), mpf("0.02783"), "diagnostic (external G_F and Delta alpha_had)")}
for H, (G, dh, tag) in cases.items():
    inp = dict(G_mu=G, MZ=MZ, alpha_bar=al / (1 - dl - dh), mt=mt, mH=mH, alpha_s=als, mb=mb, mc=mc, mtau=mtau)
    R = W.compute(inp); S = f"g_{H}"
    info(S, "G_mu GeV^-2", tag, G); info(S, "1/alpha_bar", "", 1 / inp["alpha_bar"]); info(S, "s^2 (eq. 303)", "", R["s2"])
    info(S, "Delta rho round-f form", "3 G_mu m_t^2/(8sqrt2 pi^2) x QCD (comparison only)", 3 * G * mt**2 / (8 * sqrt(2) * pi**2) * qcd)
    info(S, "rho_l = (2 g_Al)^2", "effective", R["rho_l"]); info(S, "V_A", "", R["V"]["A"]); info(S, "V_R", "", R["V"]["R"]); info(S, "V_nu", "", R["V"]["nu"])
    info(S, "phi+delta phi (Zbb)", "", R["phi"] + R["dphi"]); info(S, "mhat_b(M_Z) GeV", "", R["mb_MZ"]); info(S, "mhat_c(M_Z) GeV", "", R["mc_MZ"])
    info(S, "m_W GeV (eq. 31, info only)", "not scored in round g", R["mW_over_mZ"] * MZ)
    if H == "H1":
        note = "confirms only if z<=1 and validation passed" + ("" if VALID else " -- VALIDATION FAILED: not confirmable")
    else:
        note = "never confirmed (" + ("external" if H == "H2" else "diagnostic") + ")"
    emit(S, "Gamma_Z/M_Z", "LEPTOP effective couplings", R["Gamma_Z"] / MZ, *ref("Gamma_Z_over_M_Z"), note)
    emit(S, "Gamma_Z GeV", "", R["Gamma_Z"], *ref("Gamma_Z_GeV"), "frozen-pending")
    emit(S, "Gamma_inv MeV", "", R["Gamma_inv"] * 1000, *ref("Gamma_inv_MeV"), "frozen-pending")
    emit(S, "Gamma_ll MeV", "", R["Gamma_e"] * 1000, *ref("Gamma_ll_MeV"), "frozen-pending")
    emit(S, "R_ell", "", R["R_ell"], *ref("R_ell_derived"), "frozen-pending")
    emit(S, "R_b", "", R["R_b"], *ref("R_b"), "frozen-pending")
    emit(S, "R_c", "", R["R_c"], *ref("R_c"), "frozen-pending")
    emit(S, "sigma_had0 nb", "", R["sigma_had0_GeVm2"] * HB, *ref("sigma_had0_nb"), "frozen-pending")
    emit(S, "sin2_eff_lept", "held-out check", R["sin2_eff"], *ref("sin2_eff_lept"), "held-out")
write()
