#!/usr/bin/env python3
"""Scoring step of 2026-10-02c (after REFINEMENTS_2026-10-02c was committed): targets, held-out members, T_CMB checks.

  python tools/score_2026_10_02c.py --hub <FSOT-2.1-Lean @ 6f9c2560> --out audit/score_2026-10-02c.tsv
"""
import argparse, json, re, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
ap = argparse.ArgumentParser(); ap.add_argument("--hub", required=True); ap.add_argument("--out", required=True); a = ap.parse_args()
hub = Path(a.hub).resolve(); sys.path.insert(0, str(hub / "vendor"))
import fsot_compute as F  # noqa: E402
from mpmath import mpf, sqrt, nstr, fabs, cbrt  # noqa: E402
fr = json.load(open(ROOT / "docs/freezes/REFINEMENTS_2026-10-02c.json", encoding="utf-8"))
refs = {}
for line in open(ROOT / "reference/published_2026-10-02.tsv", encoding="utf-8"):
    if line.startswith("#") or not line.strip(): continue
    f = line.rstrip("\n").split("\t"); f += [""] * (9 - len(f)); refs[f[0]] = f
def ref(k):
    f = refs[k]
    if f[1] == "direct": return mpf(f[2]), mpf(f[3])
    p = f[1].split(":")[1].split("/"); (ca, sa), (cb, sb) = ref(p[0]), ref(p[1]); c = ca / cb
    return c, fabs(c) * sqrt((sa / ca) ** 2 + (sb / cb) ** 2)
lin = {}
for line in open(ROOT / "reference/pin_lineage_2026-10-02.tsv", encoding="utf-8"):
    if line.startswith("#"): continue
    f = line.rstrip("\n").split("\t"); lin[f[0]] = mpf(f[5])
ame = {}
for line in open(ROOT / "reference/evidence/ame2020_ba_extracts.txt", encoding="utf-8"):
    if line.startswith("#"): continue
    body = line.split("\t", 1)[1]; m = re.match(r"^.{1,5}\s*-?\d+\s+(\d+)\s+(\d+)\s+(\d+)\s+([A-Z][a-z]?)\s", body); fl = body[m.end():].split()
    ame[f"{m.group(4)}-{m.group(3)}"] = (mpf(fl[2]) / 1000, mpf(fl[3]) / 1000)
geo = json.load(open(hub / "data/geochemistry_benchmark.json", encoding="utf-8"))["records"]
rows = []
def emit(sec, name, formula, v, c, s, note=""):
    zz = fabs(v - c) / s
    rows.append([sec, name, formula, nstr(v, 15), nstr(c, 12), nstr(s, 5), nstr(zz, 5), "PASS" if zz <= 1 else "FAIL", note]); return zz
rule = "none accepted (REFINEMENTS_2026-10-02c)"
assert fr["accepted_rules"] == []
E, PHI, G, POOF = F.E, F.PHI, F.G_CAT, F.POOF
emit("target", "Gamma_Z/M_Z", "phi^5/e^6 (bare; no rule)", PHI**5 / E**6, *ref("Gamma_Z_over_M_Z"), rule)
emit("target", "Deuteron_binding_MeV", "sqrt(e)/e+phi (bare; no rule)", sqrt(E) / E + PHI, *ref("B_H2_MeV"), rule)
emit("target", "Deuteron_mu_muN", "G^4+POOF (bare; no rule)", G**4 + POOF, *ref("mu_d_over_mu_N"), rule)
r = geo[72]; assert r["name"] == "H-2"
emit("target", "LedgerB_H-2_B/A", "geochemistry #72 (bare)", mpf(repr(r["computed"])), mpf("1.1122831"), mpf("0.0000002"), rule + "; AME2020 2H B/A 1112.2831(2) keV")
emit("held_out", "R_ell", "G^3/gamma^6 (bare)", lin["wave5|R_ell"], *ref("R_ell_derived"), "class W held-out; no rule to apply")
emit("held_out", "Y_p", "theta_S*sin(1) (bare)", lin["wave5|Y_p_He4"], *ref("Y_p"), "class T held-out; no rule to apply")
r = geo[73]; assert r["name"] == "He-3"
emit("held_out", "LedgerB_He-3_B/A", "geochemistry #73 (bare)", mpf(repr(r["computed"])), *ame["He-3"], "class B2 held-out; no rule to apply")
# T_CMB checks
T_bare = PHI**2 + F.P_BASE * fabs(F.S_COSM)
yy = (POOF * F.SUCTION) ** 2
T_cand = T_bare * (1 + yy)
obh2, eta10 = lin["wave1|Omega_b_h2"], lin["wave10|eta_baryon_photon"] * mpf(10) ** 10
T_impl = mpf("2.7255") * cbrt(274 * obh2 / eta10)
s_impl = T_impl * (mpf("0.5") / 274) / 3
for nm, v in (("T_CMB bare", T_bare), ("T_CMB C-TCMB (02b)", T_cand)):
    emit("tcmb_check", nm, "vs FIRAS (PDG 2024)", v, *ref("T0_K"))
    emit("tcmb_check", nm, "vs FSOT-internal T0 from eta_b and Omega_b_h2 pins (PDG BBN eta10 = 274 Omega_b h^2 at 2.7255 K; sigma from rounding of 274)", v, T_impl, s_impl, "internal, systematic only")
    emit("tcmb_check", nm, "vs Noterdaeme 2011 T(z) normalisation", v, *ref("T0_CO_fit"), "not independent of FIRAS")
c0, s0 = ref("T0_CO_fit")
rows.append(["tcmb_check", "discrimination", "|cand-bare|/sigma", nstr(fabs(T_cand - T_bare) / s0, 4), "Noterdaeme", nstr(s0, 3), nstr(fabs(T_cand - T_bare) / s_impl, 4), "internal", "power to separate the two T_CMB values"])
with open(a.out, "w", encoding="utf-8") as o:
    o.write("# generated by tools/score_2026_10_02c.py after docs/freezes/REFINEMENTS_2026-10-02c was committed\n#section\tname\tformula\tvalue\tcentral\tsigma\tz\tz<=1\tnote\n")
    for r in rows: o.write("\t".join(r) + "\n")
for r in rows: print(" | ".join(r))
