#!/usr/bin/env python3
"""Step 3 of DERIVATIONS_2026-10-02d, after REFINEMENTS_2026-10-02d was committed: C1 targets and held-out members (no rule accepted, so bare),
and the C2 two-nucleon deuteron.

  python tools/score_2026_10_02d.py --hub <FSOT-2.1-Lean @ 6f9c2560> --out audit/score_2026-10-02d.tsv
"""
import argparse, json, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
import fsot02d as X
from fsot02d import mpf, sqrt, pi, fabs, nstr
ap = argparse.ArgumentParser(); ap.add_argument("--hub", required=True); ap.add_argument("--out", required=True); a = ap.parse_args()
hub, F = X.setup(a.hub); ref = X.refs(); P = X.pins(); L = X.leaves(); R = X.compute(hub, F)
fr = json.load(open(X.ROOT / "docs/freezes/REFINEMENTS_2026-10-02d.json", encoding="utf-8")); assert fr["accepted_rules"] == []
rule = "no C1 rule accepted (REFINEMENTS_2026-10-02d)"
rows = []
def emit(sec, name, inputs, v, c, s, note=""):
    zz = fabs(v - c) / s
    rows.append([sec, name, inputs, nstr(v, 15), nstr(c, 12), nstr(s, 5), nstr(zz, 5), "PASS" if zz <= 1 else "FAIL", nstr((v - c) / c * 10**6, 6), note])
mud = ref("mu_d_over_mu_N")
emit("C1_target", "mu_d (pin G^4+POOF)", "bare", F.G_CAT**4 + F.POOF, *mud, rule)
s67 = R["sec67"]["H-2"]
emit("C1_target", "mu_d (Damian sec.67 #1036 C_EFF^-6/A_BLEED^9)", f"bare, {s67['source']}", s67["value"], *mud, rule)
emit("C1_target", "Gamma_Z/M_Z (pin phi^5/e^6)", "bare", P["wave5|Gamma_Z/M_Z"], *ref("Gamma_Z_over_M_Z"), rule)
mn = R["sec67"]["Mn-55"]
emit("C1_heldout", "mu Mn-55 (sec.67 #1046 G^-3+OMEGA^3)", f"bare, {mn['source']}", mn["value"], *ref("mu_Mn55"), rule + "; IAEA 3.4467(16)")
emit("C1_heldout", "R_ell (pin G^3/gamma^6)", "bare", P["wave5|R_ell"], *ref("R_ell_derived"), rule)
emit("C2", "mu_d two-nucleon (candidate)", "mu_p leaf + mu_n row(-2/3 mu_p), P_D = 5.76 % EXTERNAL (AV18)", R["mu_d_2N"], *mud, "frozen-pending; 1 external input")
emit("C2_alt", "mu_d two-nucleon, P_D = 0", "mu_p leaf + mu_n row", R["mu_d_2N_PD0"], *mud, "alternative, not a candidate")
mun_c, _ = ref("mu_n_over_mu_N"); muS = L["mu_p_over_mu_N"] + mun_c
emit("C2_diag", "mu_d two-nucleon with CODATA mu_n", "diagnostic only: mu_p leaf + CODATA mu_n, P_D 5.76 %", muS - mpf(3) / 2 * (muS - mpf(1) / 2) * mpf("0.0576"), *mud,
     "diagnostic; separates the mu_n-row error from the formula error (AV18 impulse value 0.847)")
# post-freeze diagnostic for the hub decision on v / G_F (not a candidate, not scored in any count)
s2os = 1 - (L["m_W_MeV"] / L["m_Z_MeV"]) ** 2
for lab, s2 in (("MSbar leaf", L["sin2_theta_W_MSbar"]), ("on-shell 1-(m_W/m_Z)^2 from leaves", s2os)):
    vt = 2 * L["m_W_MeV"] / 1000 * sqrt(s2) / sqrt(4 * pi / L["alpha_inv"])
    emit("diag_vev", f"v from seed_vev_GeV docstring relation 2 m_W sin(theta_W)/sqrt(4 pi alpha), s2 {lab}", "post-freeze diagnostic, not a candidate", vt, mpf("246.21965"), mpf("0.00006"),
         "reference v = (sqrt2 G_F)^-1/2 from CODATA G_F; tree level, no Delta r")
emit("diag_vev", "v from seed_vev_GeV as implemented (theta_S+e^3)/C_factor^6/1000*phi", "hub function value", R["v"], mpf("246.21965"), mpf("0.00006"), "explains the part-A/B G_F failure")
with open(a.out, "w", encoding="utf-8") as o:
    o.write("# generated by tools/score_2026_10_02d.py after docs/freezes/REFINEMENTS_2026-10-02d was committed\n#section\tname\tinputs\tvalue\tcentral\tsigma\tz\tz<=1\tppm\tnote\n")
    for r in rows: o.write("\t".join(r) + "\n")
for r in rows: print(" | ".join(r))
