#!/usr/bin/env python3
"""Round-aq scores under audit/FREEZE_2026-10-02aq (committed first). z-only, dimensionless ratios; FSOT-only inputs.
AQ-1 shell-averaged r_V^2 diagnostic (audit/rv_2026-10-02aq_{A,B}_j*.json) with valence/sea/PV split; AQ-0 level-C job status.
  python tools/score_2026_10_02aq.py --hub <FSOT-2.1-Lean @ 6f9c2560> --out audit/score_2026-10-02aq.tsv
"""
import argparse, json, math, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
import fsot02d as X
from fsot02d import mpf, sqrt, pi, ln, fabs, nstr
from mpmath import zeta
ap = argparse.ArgumentParser(); ap.add_argument("--hub", required=True); ap.add_argument("--out", required=True); a = ap.parse_args()
hub, F = X.setup(a.hub); L = X.leaves(); P = X.pins(); ref = X.refs(); R_ = Path(__file__).resolve().parents[1]
rows = []
def emitz(sec, name, inputs, v, c, s, th=0, cls="", note=""):
    v, c, s, th = mpf(v), mpf(c), mpf(s), mpf(th); sig = sqrt(s**2 + th**2); z = fabs(v - c) / sig
    rows.append([sec, name, inputs, nstr(v, 12), nstr(c, 10), nstr(sig, 4), nstr(z, 5), "agrees" if z <= 1 else "miss", nstr((v - c) / c * 100, 5) + " %", cls, note]); return z
def info(sec, name, inputs, v, cls="", note=""): rows.append([sec, name, inputs, nstr(mpf(v), 12), "-", "-", "-", "info", "-", cls, note])
def rec(sec, name, verdict, note): rows.append([sec, name, "-", "-", "-", "-", "-", verdict, "-", "-", note])
J = lambda f: json.loads((R_ / f).read_text(encoding="utf-8"))
mpM = X.kg_to_GeV(L["m_p_kg"]) * 1000
s = "AQ-1"; Mr = mpf(J("audit/murun_2026-10-02ag_K14_D14_k12.json")["inputs"]["M_over_mp"]); hbc = mpf("0.1973269804"); mpG = mpM / 1000; fm2 = (hbc / mpG)**2 / Mr**2   # fm^2 per unit 1/M^2
def avg(v): return sum(v) / len(v)
lev = {}
for L_ in ("A", "B"):
    S_ = [J("audit/rv_2026-10-02aq_%s_j%d.json" % (L_, j)) for j in range(4)]
    for e_ in S_: info(s, "AQ-1 level %s box j=%d (kmax %g, D %s): r_V^2 M^2" % (L_, e_["j"], e_["kmax"], nstr(mpf(e_["D"]), 8)), "I[r^2]/I[1]", mpf(e_["Ir2"]) / mpf(e_["I1"]), "diagnostic", "I[1] %s; max |imag| %s; %s s" % (nstr(mpf(e_["I1"]), 10), e_["max_imag"], e_["seconds"]))
    P = {k: [avg([mpf(e_[k][i]) for e_ in S_]) for i in range(2)] for k in ("I_val", "I_sea", "I_pv")}; I1 = sum(P[k][0] for k in P); Ir2 = sum(P[k][1] for k in P)
    r2 = Ir2 / I1; lev[L_] = r2
    info(s, "AQ-1 level %s averaged r_V^2 (fm^2)" % L_, "<I[r^2]>/<I[1]>, 4 boxes", r2 * fm2, "FSOT · intermediate", "r_V^2 M^2 %s" % nstr(r2, 8))
    sv = P["I_sea"][1] + P["I_pv"][1]; s1_ = P["I_sea"][0] + P["I_pv"][0]
    info(s, "AQ-1 level %s split: valence share of I[1] and of I[r^2]" % L_, "valence = terms with the valence level occupied", P["I_val"][0] / I1, "diagnostic",
         "I[r^2] share %s; valence-only r^2 %s fm^2; sea+PV share of I[1] %s, of I[r^2] %s; sea+PV-only r^2 %s fm^2; PV cancels %s %% of the bare sea I[r^2] (%s %% of I[1])" % (
         nstr(P["I_val"][1] / Ir2, 5), nstr(P["I_val"][1] / P["I_val"][0] * fm2, 5), nstr(s1_ / I1, 5), nstr(sv / Ir2, 5), nstr(sv / s1_ * fm2, 5), nstr(-P["I_pv"][1] / P["I_sea"][1] * 100, 4), nstr(-P["I_pv"][0] / P["I_sea"][0] * 100, 4)))
ch = (lev["B"] - lev["A"]) / lev["B"]; stable = fabs(ch) <= mpf("0.02")
r2c = (mpf("0.84075")**2 + mpf("0.1155")) * (mpG / hbc)**2; r2s = sqrt((2 * mpf("0.84075") * mpf("0.00064"))**2 + mpf("0.0017")**2) * (mpG / hbc)**2
zr = emitz(s, "AQ-1 r_V^2 m_p^2, level B shell-averaged (validation)", "FSOT soliton", lev["B"] / Mr**2, r2c, r2s, fabs(lev["B"] - lev["A"]) / Mr**2, "validation (PDG r_p, <r_n^2>)", "r_V^2 %s fm^2 vs 0.82236(201); A -> B change %s %%" % (nstr(lev["B"] * fm2, 6), nstr(ch * 100, 3)))
verdict = "numerical" if zr <= 1 else ("physical" if stable else "undetermined")
rec(s, "AQ-1 verdict on the round-ap 22 % excess", verdict, "stable %s (A -> B %s %%), validation z %s; %s" % (stable, nstr(ch * 100, 3), nstr(zr, 4),
    "the excess comes from the PV-regularised sea (pion-cloud) part of the 1/I sum; no vacuum term (vanishes identically) or valence-PV term is missing; the ap chain is not carried and Delta alpha_had, G_F, Gamma_Z/M_Z are not rescored; the FSOT correction branch is not frozen this round (see report)" if verdict == "physical" else ""))
rec("AQ-0", "AQ-0 level C (kmax 16) job", "running at commit (sample j=0 committed)", "paused while AQ-1 ran and during cpp_check; the round-ap B -> C rule is applied in the round it finishes")
rec("GATE", "record rows of the 91", "unchanged", "z-only; 88/91 since owner record commit b99fc29")
with open(a.out, "w", encoding="utf-8", newline="\n") as o:
    o.write("# generated by tools/score_2026_10_02aq.py under audit/FREEZE_2026-10-02aq (committed first)\n#section\tname\tinputs\tvalue\tcentral\tsigma\tz\tverdict\trel\tclass\tnote\n")
    for r_ in rows: o.write("\t".join(str(x_) for x_ in r_) + "\n")
print("done", len(rows))
