#!/usr/bin/env python3
"""Round-i branch scoring under audit/FREEZE_2026-10-02i (committed first). Order fixed by the freeze: PDG-input validations of HAD-1 and
HAD-2, then FSOT-input scores, then GZ-1 H1-i with the HAD-2 Delta alpha_had. GZ-1 building blocks are copied verbatim from
tools/score_2026_10_02h.py (FREEZE_2026-10-02h). Record values are not changed.

  python tools/score_2026_10_02i.py --hub <FSOT-2.1-Lean @ 6f9c2560> --out audit/score_2026-10-02i.tsv [--validate-only]
"""
import argparse, math, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
import fsot02d as X
from fsot02d import mpf, sqrt, pi, ln, fabs, nstr
from mpmath import zeta
ap = argparse.ArgumentParser(); ap.add_argument("--hub", required=True); ap.add_argument("--out", required=True)
ap.add_argument("--validate-only", action="store_true"); a = ap.parse_args()
rows = []
def emit(sec, name, inputs, v, c, s, note=""):
    zz = fabs(v - c) / s
    rows.append([sec, name, inputs, nstr(v, 15), nstr(c, 12), nstr(s, 5), nstr(zz, 5), "PASS" if zz <= 1 else "FAIL", nstr((v - c) / c * 10**6, 6), note])
def info(sec, name, inputs, v, note=""):
    rows.append([sec, name, inputs, nstr(v, 15), "-", "-", "-", "info", "-", note])
def write():
    with open(a.out, "w") as o:
        o.write("# generated by tools/score_2026_10_02i.py under audit/FREEZE_2026-10-02i (committed first)\n#section\tname\tinputs\tvalue\tcentral\tsigma\tz\tz<=1\tppm\tnote\n")
        for r in rows: o.write("\t".join(str(x) for x in r) + "\n")
ref = X.refs(); z3 = zeta(3)

# ---- GZ-1 building blocks (hep-ph/0311148; arXiv:1401.2447)
def mw_acfw(MH, mt, MZ, dal, als):  # eqs. fitformula, pardef, fitparams
    dH = ln(MH / 100); dh = (MH / 100) ** 2; dt = (mt / mpf("174.3")) ** 2 - 1; dZ = MZ / mpf("91.1875") - 1
    da = dal / mpf("0.05907") - 1; das = als / mpf("0.119") - 1
    return (mpf("80.3779") - mpf("0.05427") * dH - mpf("0.008931") * dH**2 + mpf("0.0000882") * dH**4 + mpf("0.000161") * (dh - 1)
            - mpf("1.070") * da + mpf("0.5237") * dt - mpf("0.0679") * dt**2 - mpf("0.00179") * dH * dt + mpf("0.0000664") * dh * dt
            - mpf("0.0795") * das + mpf("114.9") * dZ)
GZC = [mpf(x) for x in "2494.24 -3.725 -2.019 1.773 -0.04554 19.63 -2.0 -0.36 0.257 58.60 -4.1 -0.53 7.6 -56.0 1.3 9256".split()]
def gz_freitas(MH, mt, MZ, dal, als):  # eq. par2, tab:fit2 row Gamma_Z, MeV -> GeV
    LH = ln(MH / mpf("125.7")); DH = MH / mpf("125.7") - 1; Dt = (mt / mpf("173.2")) ** 2 - 1; Das = als / mpf("0.1184") - 1
    Da = dal / mpf("0.059") - 1; DZ = MZ / mpf("91.1876") - 1; c = GZC
    return (c[0] + c[1] * LH + c[2] * LH**2 + c[3] * DH + c[4] * DH**2 + c[5] * Dt + c[6] * Dt**2 + c[7] * Dt * LH + c[8] * Dt * LH**2
            + c[9] * Das + c[10] * Das**2 + c[11] * Das * LH + c[12] * Das * Dt + c[13] * Da + c[14] * Da * LH + c[15] * DZ) / 1000
def gamma_w(G, MW, als): return 3 * G * MW**3 / (2 * sqrt(2) * pi) * (1 + 2 * als / (3 * pi))
def pole(M, G): return M / sqrt(1 + (G / M) ** 2)
G_ACFW, AL_ACFW, GZ_ACFW, G_FR = mpf("1.166379e-5"), 1 / mpf("137.03599976"), mpf("2.4952"), mpf("1.16638e-5")
def delta_r(MH, mt, MZ, dal, als):
    MW = mw_acfw(MH, mt, MZ, dal, als); mwb, mzb = pole(MW, gamma_w(G_ACFW, MW, als)), pole(MZ, GZ_ACFW)
    return sqrt(2) * G_ACFW * mwb**2 * (1 - mwb**2 / mzb**2) / (pi * AL_ACFW) - 1, MW
def gf_from(al, MW, MZ, dr, als, GZ):
    G = mpf("1.1663787e-5")
    for _ in range(60):
        mwb, mzb = pole(MW, gamma_w(G, MW, als)), pole(MZ, GZ)
        new = pi * al * (1 + dr) / (sqrt(2) * mwb**2 * (1 - mwb**2 / mzb**2))
        if fabs(new - G) / G < mpf(10) ** -25: return new
        G = new
    return G
def d_s(s2, als):
    fs = [(-1, -mpf(1) / 2, 1, 3), (0, mpf(1) / 2, 1, 3), (mpf(2) / 3, mpf(1) / 2, 3 * (1 + als / pi), 2), (-mpf(1) / 3, -mpf(1) / 2, 3 * (1 + als / pi), 3)]
    num = sum(n * w * 2 * (T - 2 * Q * s2) * (-2 * Q) for Q, T, w, n in fs); den = sum(n * w * ((T - 2 * Q * s2) ** 2 + T**2) for Q, T, w, n in fs)
    return num / den
def dalep(al, MZ, masses):
    return (al / (3 * pi) * sum(ln(MZ**2 / m**2) - mpf(5) / 3 for m in masses)
            + (al / pi) ** 2 * sum(ln(MZ**2 / m**2) / 4 + z3 - mpf(5) / 24 for m in masses))

# ---- (1) validations, PDG/CODATA inputs only
sec = "validation"; alC = 1 / mpf("137.035999177")

# ---- HAD-1: De Rujula-Georgi-Glashow constituent quark model (PRD 12, 147 (1975)), A_B = A_M/2
def dgg_mrho(mpi, mN):
    # pi: 2m - 0.75 x ; N: 3m - 0.375 x  (x = A/m^2)  ->  m_rho = 2m + 0.25 x
    m = (2 * mN - mpi) / 4; x = (2 * m - mpi) / mpf("0.75")
    return 2 * m + x / 4, m, x

# ---- HAD-2: quark-hadron duality R-ratio (pure-float, deterministic; printed to 10 significant digits)
Z3 = 1.2020569031595942
def beta(a, nf):  # d alpha / d ln mu^2, 4-loop MSbar (PDG 2024 QCD review eq. 9.4)
    b0 = (33 - 2 * nf) / (12 * math.pi); b1 = (153 - 19 * nf) / (24 * math.pi**2)
    b2 = (2857 - 5033 / 9 * nf + 325 / 27 * nf**2) / (128 * math.pi**3)
    b3 = ((149753 / 6 + 3564 * Z3) - (1078361 / 162 + 6508 / 27 * Z3) * nf + (50065 / 162 + 6472 / 81 * Z3) * nf**2 + 1093 / 729 * nf**3) / (256 * math.pi**4)
    return -(b0 * a**2 + b1 * a**3 + b2 * a**4 + b3 * a**5)
class AlphaS:
    def __init__(s, asMZ, MZ, mB, mD, mtau, h=1e-3):
        s.MZ, s.mB, s.mD, s.mtau, s.h = MZ, mB, mD, mtau, h
        s.t0 = math.log(MZ**2); s.tlo = math.log(mtau**2); s.thi = math.log((1e5) ** 2)
        def nf(t): return 5 if t >= math.log(mB**2) else (4 if t >= math.log(mD**2) else 3)
        def run(t, a, t1):
            n = max(1, int(round(abs(t1 - t) / h))); dt = (t1 - t) / n; out = [a]
            for _ in range(n):
                f = nf(t + 0.5 * dt)
                k1 = beta(a, f); k2 = beta(a + 0.5 * dt * k1, f); k3 = beta(a + 0.5 * dt * k2, f); k4 = beta(a + dt * k3, f)
                a += dt * (k1 + 2 * k2 + 2 * k3 + k4) / 6; t += dt; out.append(a)
            return out, dt
        s.down, s.ddn = run(s.t0, asMZ, s.tlo); s.up, s.dup = run(s.t0, asMZ, s.thi)
    def __call__(s, mu):
        t = math.log(mu**2)
        if t <= s.tlo: return s.down[-1]
        arr, d = (s.down, s.ddn) if t < s.t0 else (s.up, s.dup)
        x = (t - s.t0) / d; i = min(int(x), len(arr) - 2); f = x - i
        return arr[i] * (1 - f) + arr[i + 1] * f
def gl_nodes(n):  # Gauss-Legendre by Newton iteration (pure Python, deterministic)
    xs, ws = [], []
    for i in range(1, n + 1):
        x = math.cos(math.pi * (i - 0.25) / (n + 0.5))
        for _ in range(100):
            p0, p1 = 1.0, x
            for k in range(2, n + 1): p0, p1 = p1, ((2 * k - 1) * x * p1 - (k - 1) * p0) / k
            dp = n * (x * p1 - p0) / (x * x - 1); dx = p1 / dp; x -= dx
            if abs(dx) < 1e-16: break
        xs.append(x); ws.append(2 / ((1 - x * x) * dp * dp))
    return xs, ws
GX, GW = gl_nodes(48)
def dalpha_had(alpha, MZ, asMZ, mtau, mpi, mK, mD, mB):
    AS = AlphaS(asMZ, MZ, mB, mD, mtau)
    flav = [(4 * mpi**2, 4 / 9), (4 * mpi**2, 1 / 9), (4 * mK**2, 1 / 9), (4 * mD**2, 4 / 9), (4 * mB**2, 1 / 9)]
    MZ2 = MZ**2
    def R(s):
        open_ = [q for th, q in flav if s > th]; nf = len(open_)
        aa = AS(math.sqrt(s)) / math.pi
        K = 1 + aa + (1.9857 - 0.1152 * nf) * aa**2 + (-6.63694 - 1.20013 * nf - 0.00518 * nf**2) * aa**3
        return 3 * sum(open_) * K
    RZ = R(MZ2); smin = flav[0][0]
    def g(t):
        s = math.exp(t); return (R(s) - RZ) * MZ2 / (MZ2 - s) if abs(MZ2 - s) > 1e-9 * MZ2 else 0.0
    edges = sorted({math.log(th) for th, _ in flav} | {math.log(MZ2)})
    pts = []
    for lo, hi in zip(edges, edges[1:]):
        n = max(1, int(math.ceil((hi - lo) / 0.5))); pts += [lo + (hi - lo) * k / n for k in range(n + 1)][:-1]
    pts.append(edges[-1]); top = math.log(MZ2) + 40.0
    n = 80; pts += [edges[-1] + (top - edges[-1]) * k / n for k in range(1, n + 1)]
    tot = 0.0
    for lo, hi in zip(pts, pts[1:]):
        c, w = 0.5 * (hi + lo), 0.5 * (hi - lo)
        tot += w * sum(wi * g(c + w * xi) for xi, wi in zip(GX, GW))
    tot += RZ * math.log((MZ2 - smin) / smin)
    return alpha / (3 * math.pi) * tot, AS

def f10(x): return mpf(float("%.10g" % x))  # deterministic 10-significant-digit hand-off from the float integrator

# ---- (1) validations, PDG/CODATA inputs only
sec = "validation"; alC = 1 / mpf("137.035999177")
v_mrho, v_m, v_x = dgg_mrho(mpf("139.57039"), mpf("938.27208943"))
emit(sec, "HAD-1 m_rho MeV (DGG, PDG m_pi, m_p)", "constituent m %s MeV, A/m^2 %s MeV" % (nstr(v_m, 8), nstr(v_x, 8)), v_mrho, mpf("775.26"), mpf("0.23"),
     "validation criterion |rel| <= 5 %")
VAL1 = fabs(v_mrho - mpf("775.26")) / mpf("775.26") <= mpf("0.05")
info(sec, "HAD-1 VALIDATED", "", mpf(1 if VAL1 else 0), "1 = pass, 0 = fail")
dv, ASv = dalpha_had(float(alC), 91.1880, 0.1180, 1.77693, 0.13957039, 0.493677, 1.86966, 5.27941)
info(sec, "HAD-2 alpha_s(m_tau) (4-loop, PDG alpha_s(M_Z))", "check vs PDG 0.314(14)", f10(ASv(1.77693)))
emit(sec, "HAD-2 Delta alpha_had^(5) (duality, PDG inputs)", "PDG masses, alpha_s 0.1180", f10(dv), mpf("0.02783"), mpf("0.00006"),
     "validation criterion |dev| <= 0.00029")
VAL2 = abs(dv - 0.02783) <= 0.00029
info(sec, "HAD-2 VALIDATED", "", mpf(1 if VAL2 else 0), "1 = pass, 0 = fail (then nothing from HAD-2 is confirmable)")
if a.validate_only:
    write(); print("validation only; VAL1 =", VAL1, "VAL2 =", VAL2); sys.exit(0)

# ---- (2) FSOT inputs
hub, F = X.setup(a.hub); P = X.pins(); L = X.leaves()
MZ, MW, al = L["m_Z_MeV"] / 1000, L["m_W_MeV"] / 1000, 1 / L["alpha_inv"]
mt = L["m_t_over_m_W"] * MW; MH = L["m_H_MeV"] / 1000; als = 2 * (F.POOF / F.PSI_CON) ** 2; mtau = L["m_tau_MeV"] / 1000
mp_MeV = X.kg_to_GeV(L["m_p_kg"]) * 1000
r1, m1, x1 = dgg_mrho(L["m_pi_pm_MeV"], mp_MeV)
emit("HAD-1", "m_rho MeV (DGG, FSOT m_pi+-, m_p)", "constituent m %s MeV" % nstr(m1, 8), r1, mpf("775.26"), mpf("0.23"),
     "validation " + ("passed" if VAL1 else "FAILED: route rejected"))
dF, ASF = dalpha_had(float(al), float(MZ), float(als), float(mtau), float(L["m_pi_pm_MeV"]) / 1000, float(L["m_K_pm_MeV"]) / 1000,
                     float(L["m_D_pm_MeV"]) / 1000, 5.27941)
info("HAD-2", "alpha_s(m_tau) (4-loop from FSOT alpha_s seed)", "", f10(ASF(float(mtau))))
dhF = f10(dF)
emit("HAD-2", "Delta alpha_had^(5) (duality, FSOT inputs; m_B external)", "FSOT alpha, M_Z, alpha_s, m_tau, m_pi, m_K, m_D", dhF, mpf("0.02783"), mpf("0.00006"),
     "validation " + ("passed" if VAL2 else "FAILED: not confirmable"))
dl = dalep(al, MZ, [X.kg_to_GeV(L["m_e_kg"]), X.kg_to_GeV(L["m_mu_kg"]), mtau])
ds = d_s(L["sin2_theta_W_MSbar"], als); s2leaf = 1 - (MW / MZ) ** 2
S = "GZ-1_H1-i"; dal = dl + dhF
dr, MWfit = delta_r(MH, mt, MZ, dal, als)
GZ = GZ_ACFW
for _ in range(30):
    G = gf_from(al, MW, MZ, dr, als, GZ)
    GZfit = gz_freitas(MH, mt, MZ, dal, als); dS2 = s2leaf - (1 - (MWfit / MZ) ** 2)
    new = GZfit * (G / G_FR) * (1 + ds * dS2)
    if fabs(new - GZ) < mpf(10) ** -15: GZ = new; break
    GZ = new
info(S, "Delta alpha", "FSOT lep (round f) + HAD-2", dal); info(S, "M_W^fit GeV (ACFW)", "", MWfit)
info(S, "Delta r (complete SM, ACFW)", "", dr, "ACFW convention")
emit(S, "G_F GeV^-2", "", G, *ref("G_F_GeVm2"), "")
ok = VAL2  # round-h V1, V2 passed (audit/score_2026-10-02h.tsv)
emit(S, "Gamma_Z/M_Z", "GZ-1 with HAD-2", GZ / MZ, *ref("Gamma_Z_over_M_Z"),
     "confirms only if V1, V2 (round h, passed) and HAD-2 validation pass and z<=1" + ("" if ok else " -- HAD-2 VALIDATION FAILED: not confirmable"))
emit(S, "Gamma_Z GeV", "GZ-1 with HAD-2", GZ, *ref("Gamma_Z_GeV"), "")
write()
